name: StoryToVideoApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  StoryToVideo:
    path: StoryToVideo

targets:
  StoryToVideoApp:
    type: application
    platform: iOS
    sources:
      - path: App
    dependencies:
      - package: StoryToVideo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.StoryToVideoApp
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: StoryToVideo
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
